In [2]:
a=int(input("enter a number"))
b=int(input("enter the second number"))
print("available options are : ")
print("1.ADDITION")
print("2.SUBSTRACTION")
print("3.MULTIPLICATION")
print("4.DIVISION")
option = input("enter the option : ")

if(option=="1"):
    print(a+b)
elif(option=="2"):
    print(a-b)
elif(option=="3"):
    print(a*b)
elif(option=="4"):
    print(a/b)
else:
    print("invalid")

enter a number2
enter the second line3
available options are : 
1.ADDITION
2.SUBSTRACTION
3.MULTIPLICATION
4.DIVISION
enter the option : 1
5


In [6]:
a=int(input("enter a number"))
b=int(input("enter a number"))
print(a and b)
print(a or b)
print(a == b)
print(a > b)
print(a < b)
print(a != b)

enter a number2
enter a number2
2
2
True
False
False
False


In [6]:
a=int(input("enter first number : " ))
b=int(input("enter second number : " ))
c=int(input("enter third number : " ))

if(a>b and a>c):
    print(a)
elif(b>a and b>c):
    print(b)
else:
    print(str(c) +" is largest")

enter first number : 1
enter second number : 2
enter third number : 3
3 is largest


In [13]:
a={"name":"adithyan",
    "age":20}
b={"fname":"adithyan k",
   "age":20}

a.update(b)
print(a)

{'name': 'adithyan', 'age': 20, 'fname': 'adithyan k'}


In [7]:
a=[1,2,3,4]
a.append(5)
print(a)
a.pop
print(a)
a.remove(1)
print(a)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[2, 3, 4, 5]


In [1]:
import numpy as np

# 1. Define the 2x2 matrix A
A = np.array([[4, 11],
              [14, 5]], dtype=float)

# 2. Compute the SVD
# np.linalg.svd returns U, a 1D array of singular values, and V^T
U, s, Vt = np.linalg.svd(A)

# 3. Convert the 1D singular values array into a 2x2 diagonal matrix (Sigma)
Sigma = np.diag(s)

# 4. Display the results nicely
print("--- Matrix U (Left Singular Vectors) ---")
print(np.round(U, 4))

print("\n--- Matrix Sigma (Singular Values Diagonal) ---")
print(np.round(Sigma, 4))

print("\n--- Matrix Vt (Right Singular Vectors Transposed) ---")
print(np.round(Vt, 4))

# 5. Optional Verification: Multiply U * Sigma * Vt to reconstruct A
A_reconstructed = U @ Sigma @ Vt
print("\n--- Verification (U * Sigma * Vt) ---")
print(np.round(A_reconstructed, 4))


--- Matrix U (Left Singular Vectors) ---
[[-0.5684 -0.8228]
 [-0.8228  0.5684]]

--- Matrix Sigma (Singular Values Diagonal) ---
[[17.2534  0.    ]
 [ 0.      7.7666]]

--- Matrix Vt (Right Singular Vectors Transposed) ---
[[-0.7994 -0.6008]
 [ 0.6008 -0.7994]]

--- Verification (U * Sigma * Vt) ---
[[ 4. 11.]
 [14.  5.]]


In [2]:
import numpy as np

# 1. Define a 3x3 matrix A
A = np.array([
    [3.0, 2.0, 2.0],
    [2.0, 3.0, -2.0],
    [1.0, 1.0, 2.0]
], dtype=float)

# 2. Compute the SVD
# np.linalg.svd returns U (3x3), s (1x3 array of singular values), and Vt (3x3)
U, s, Vt = np.linalg.svd(A)

# 3. Convert the 1D singular values array into a 3x3 diagonal matrix (Sigma)
Sigma = np.diag(s)

# 4. Display the results rounded to 4 decimal places
print("--- Matrix U (3x3 Left Singular Vectors) ---")
print(np.round(U, 4))

print("\n--- Matrix Sigma (3x3 Singular Values Diagonal) ---")
print(np.round(Sigma, 4))

print("\n--- Matrix Vt (3x3 Right Singular Vectors Transposed) ---")
print(np.round(Vt, 4))

# 5. Verification: Reconstruct original matrix A
A_reconstructed = U @ Sigma @ Vt
print("\n--- Verification (U @ Sigma @ Vt) ---")
print(np.round(A_reconstructed, 4))


--- Matrix U (3x3 Left Singular Vectors) ---
[[-0.7347  0.411  -0.5398]
 [-0.5902 -0.7795  0.2097]
 [-0.3346  0.4727  0.8153]]

--- Matrix Sigma (3x3 Singular Values Diagonal) ---
[[5.2465 0.     0.    ]
 [0.     3.4894 0.    ]
 [0.     0.     0.5462]]

--- Matrix Vt (3x3 Right Singular Vectors Transposed) ---
[[-0.7088 -0.6813 -0.1826]
 [ 0.042  -0.2992  0.9533]
 [-0.7041  0.6681  0.2407]]

--- Verification (U @ Sigma @ Vt) ---
[[ 3.  2.  2.]
 [ 2.  3. -2.]
 [ 1.  1.  2.]]
